from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import os

def delete_paragraph(paragraph):
    p = paragraph._element
    p.getparent().remove(p)
    paragraph._p = paragraph._element = None

def generate_full_docs():
    filepath = 'Letter-Head.docx'
    doc = Document(filepath)
    
    # 1. Clean previous generations and keep ONLY the original letterhead header (first 3 paragraphs)
    while len(doc.paragraphs) > 3:
        delete_paragraph(doc.paragraphs[-1])
        
    # Remove any tables that were generated by my previous scripts
    for table in doc.tables:
        table._element.getparent().remove(table._element)
        
    # 2. Setup Professional Styles
    styles = doc.styles
    
    # Title Style
    if 'CustomTitle' not in styles:
        title_style = styles.add_style('CustomTitle', WD_STYLE_TYPE.PARAGRAPH)
    else:
        title_style = styles['CustomTitle']
    title_font = title_style.font
    title_font.name = 'Arial'
    title_font.size = Pt(22)
    title_font.color.rgb = RGBColor(0, 51, 102)
    title_font.bold = True
    
    # Heading 1
    if 'Heading 1' not in styles:
        h1 = styles.add_style('Heading 1', WD_STYLE_TYPE.PARAGRAPH)
    else:
        h1 = styles['Heading 1']
    h1.font.name = 'Arial'
    h1.font.size = Pt(16)
    h1.font.color.rgb = RGBColor(0, 102, 204)
    h1.font.bold = True
    
    # Heading 2
    if 'Heading 2' not in styles:
        h2 = styles.add_style('Heading 2', WD_STYLE_TYPE.PARAGRAPH)
    else:
        h2 = styles['Heading 2']
    h2.font.name = 'Arial'
    h2.font.size = Pt(14)
    h2.font.color.rgb = RGBColor(64, 64, 64)
    h2.font.bold = True
    
    # Normal Text (Force Arial / Aptos equivalent)
    if 'Normal' in styles:
        normal = styles['Normal']
        normal.font.name = 'Arial'
        normal.font.size = Pt(11)
        
    # CodeBlock
    if 'CodeBlock' not in styles:
        code_style = styles.add_style('CodeBlock', WD_STYLE_TYPE.PARAGRAPH)
    else:
        code_style = styles['CodeBlock']
    code_font = code_style.font
    code_font.name = 'Consolas'
    code_font.size = Pt(10)
    code_font.color.rgb = RGBColor(40, 44, 52)
    
    # --- DOCUMENT GENERATION ---
    doc.add_paragraph()
    
    title = doc.add_paragraph('Multimodal Agentic WhatsApp AI Automation Platform', style='CustomTitle')
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle = doc.add_paragraph('Comprehensive Technical Project Documentation', style='Heading 2')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph('Version 1.0.0 | Generated Dynamically\n').alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Section 1: Overview
    doc.add_heading('1. Project Overview', level=1)
    doc.add_paragraph('The Multimodal Agentic WhatsApp AI Automation Platform is an advanced, high-performance system designed to handle complex customer interactions via WhatsApp. It leverages a LangGraph-based multi-agent architecture, allowing intelligent routing of user intents across specialized AI agents. The system natively supports multimodal inputs, including voice notes (via faster-whisper) and images (via Moondream2 and PaddleOCR).')
    
    # Section 2: Architecture
    doc.add_heading('2. System Architecture & Tech Stack', level=1)
    doc.add_paragraph('The platform is built on a modern, asynchronous Python backend, optimized for high throughput and robust AI integrations.')
    
    table = doc.add_table(rows=1, cols=2)
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Component'
    hdr_cells[1].text = 'Technology'
    
    techs = [
        ('Backend Framework', 'FastAPI (Python 3.11+)'),
        ('Primary Database', 'PostgreSQL'),
        ('Vector Store (RAG)', 'pgvector (Cosine Similarity)'),
        ('Cache / Task Queue', 'Redis & ARQ Worker'),
        ('Agent Orchestration', 'LangGraph & LangChain'),
        ('LLM Providers', 'OpenAI, Ollama (Local fallback)'),
        ('Speech-to-Text (STT)', 'faster-whisper (Int8, CPU optimized)'),
        ('Text-to-Speech (TTS)', 'Piper TTS (ONNX)'),
        ('Vision / OCR', 'Moondream2 & PaddleOCR'),
        ('API Integration', 'Meta WhatsApp Cloud API (Webhooks)')
    ]
    for comp, tech in techs:
        row_cells = table.add_row().cells
        row_cells[0].text = comp
        row_cells[1].text = tech
        
    doc.add_paragraph()
    
    # Section 3: Directory
    doc.add_heading('3. Directory Structure', level=1)
    doc.add_paragraph('The project is organized in a modular structure to separate concerns and allow scalability.')
    
    dirs = [
        ('src/whatsapp_agent/', 'Core backend application source code.'),
        ('src/whatsapp_agent/agents/', 'Contains all 9 specialized LangGraph agents (Supervisor, Sales, Lead, etc).'),
        ('src/whatsapp_agent/api/', 'FastAPI routes, endpoints, and webhook handlers.'),
        ('src/whatsapp_agent/core/', 'Core configuration, Pydantic settings, and logging.'),
        ('src/whatsapp_agent/services/', 'Business logic interfaces for Database, LLM, and WhatsApp API.'),
        ('apps/web/', 'Frontend dashboard (React/TypeScript).'),
        ('docker/', 'Docker Compose configurations for infrastructure deployment.')
    ]
    
    for d, desc in dirs:
        p = doc.add_paragraph()
        p.add_run(f'{d} ').bold = True
        p.add_run(f'- {desc}')
        
    # Section 4: Agent Architecture
    doc.add_heading('4. Agent Architecture', level=1)
    doc.add_paragraph('The platform uses a sophisticated multi-agent orchestration model driven by LangGraph. A central Supervisor Agent intercepts incoming WhatsApp messages, classifies the user intent, and delegates the task to a specialized sub-agent.')
    
    table2 = doc.add_table(rows=1, cols=3)
    hdr_cells2 = table2.rows[0].cells
    hdr_cells2[0].text = 'Agent Name'
    hdr_cells2[1].text = 'Responsibility'
    hdr_cells2[2].text = 'Status'
    
    agents = [
        ('Supervisor', 'Intent classification & workflow routing', 'Implemented'),
        ('Knowledge', 'RAG-based FAQ answering via pgvector', 'Implemented'),
        ('Lead', 'Data extraction for lead qualification', 'Partial (Bug identified)'),
        ('Scheduling', 'Calendar and appointment management', 'Implemented'),
        ('CRM', 'HubSpot/Frappe ticket retrieval', 'Implemented'),
        ('Media', 'Vision/OCR analysis of images', 'Implemented'),
        ('Sales', 'Product recommendations and pricing', 'Implemented'),
        ('Human Escalation', 'Halts AI responses for human takeover', 'Implemented')
    ]
    
    for agent, resp, status in agents:
        row_cells = table2.add_row().cells
        row_cells[0].text = agent
        row_cells[1].text = resp
        row_cells[2].text = status
        
    doc.add_paragraph()
        
    # Section 5: Environments
    doc.add_heading('5. Environment Variables', level=1)
    doc.add_paragraph('Core configuration is managed securely via environment variables (loaded by Pydantic Settings).')
    
    table3 = doc.add_table(rows=1, cols=3)
    hdr_cells3 = table3.rows[0].cells
    hdr_cells3[0].text = 'Variable'
    hdr_cells3[1].text = 'Purpose'
    hdr_cells3[2].text = 'Example / Placeholder'
    
    envs = [
        ('WHATSAPP_API_TOKEN', 'Bearer token for Meta API', '<SECRET_TOKEN>'),
        ('WHATSAPP_WEBHOOK_VERIFY_TOKEN', 'HMAC verification for webhooks', '<SECRET_VERIFY>'),
        ('DATABASE_URL', 'PostgreSQL connection string', 'postgresql://user:pass@localhost:5432/db'),
        ('REDIS_URL', 'Redis connection string', 'redis://localhost:6379/0'),
        ('OPENAI_API_KEY', 'Primary LLM API Key', 'sk-...'),
        ('STRAPI_API_URL', 'Headless CMS Integration URL', 'http://localhost:1337'),
        ('ADOBE_MARKETO_CLIENT_ID', 'Adobe Experience Cloud Sync', '<CLIENT_ID>')
    ]
    
    for env, purp, ex in envs:
        row_cells = table3.add_row().cells
        row_cells[0].text = env
        row_cells[1].text = purp
        row_cells[2].text = ex
        
    doc.add_paragraph()
        
    # Section 6: Security
    doc.add_heading('6. Security & Governance', level=1)
    security = [
        ('Webhook Verification', 'HMAC-SHA256 signature validation on all incoming Meta requests to prevent spoofing.'),
        ('Token Governance', 'Strict session-level input/output token budgets to prevent LLM cost overruns and infinite loops.'),
        ('Rate Limiting', 'Global sliding-window rate limits on the FastAPI endpoints.'),
        ('RBAC Tools', 'External integrations require explicit authentication and are sandboxed based on user roles.')
    ]
    for title, desc in security:
        p = doc.add_paragraph()
        p.add_run(f'• {title}: ').bold = True
        p.add_run(desc)
        
    # Section 7: Limitations
    doc.add_heading('7. Known Limitations & TODOs', level=1)
    doc.add_paragraph('Based on the codebase audit, the following limitations and bugs are currently present and require resolution prior to production deployment:')
    todos = [
        'Lead Agent Bug: The Lead Agent is missing its system prompt, causing LLM hallucinations.',
        'Dashboard API: The frontend dashboard is built but not yet connected to the backend API endpoints.',
        'Multimodal Pipelines: STT and Vision pipelines are defined in settings but need full integration into the ARQ worker queue for async processing.'
    ]
    for todo in todos:
        p = doc.add_paragraph()
        p.add_run('• ')
        p.add_run(todo)
        
    # Section 8: Future
    doc.add_heading('8. Future Enhancements', level=1)
    future = [
        'Strapi Headless CMS Integration for dynamic knowledge base syncing.',
        'Adobe Experience Cloud Syncing for automated email retargeting of qualified leads.',
        'Proactive Outbound Campaigns for appointment reminders via WhatsApp.',
        'Live Sentiment Analysis during calls to trigger automatic human handoffs.',
        'ERP Write Actions to allow authenticated employees to open support tickets via WhatsApp.'
    ]
    for feat in future:
        p = doc.add_paragraph()
        p.add_run('• ')
        p.add_run(feat)
        
    doc.save(filepath)
    print(f"Final Project Documentation successfully generated in {filepath}")

if __name__ == "__main__":
    generate_full_docs()
