import os
from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

def scan_project(root_dir):
    stats = {
        'python_files': 0,
        'ts_files': 0,
        'tsx_files': 0,
        'total_size_mb': 0
    }
    
    directories = []
    
    for root, dirs, files in os.walk(root_dir):
        # Ignore hidden dirs and environments
        dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ['__pycache__', 'node_modules']]
        
        rel_path = os.path.relpath(root, root_dir)
        if rel_path == '.':
            directories = dirs.copy()
            
        for file in files:
            file_path = os.path.join(root, file)
            try:
                stats['total_size_mb'] += os.path.getsize(file_path) / (1024 * 1024)
            except OSError:
                pass
                
            if file.endswith('.py'):
                stats['python_files'] += 1
            elif file.endswith('.ts'):
                stats['ts_files'] += 1
            elif file.endswith('.tsx'):
                stats['tsx_files'] += 1
                
    return stats, directories

def append_scan_results():
    filepath = 'Letter-Head.docx'
    doc = Document(filepath)
    
    # Styles
    styles = doc.styles
    if 'Heading 1' not in styles:
        h1_style = styles.add_style('Heading 1', WD_STYLE_TYPE.PARAGRAPH)
        h1_font = h1_style.font
        h1_font.name = 'Arial'
        h1_font.size = Pt(16)
        h1_font.color.rgb = RGBColor(0, 102, 204)
        
    doc.add_paragraph('\n')
    doc.add_heading('Codebase Dynamic Scan Results', level=1)
    
    stats, top_dirs = scan_project('.')
    
    doc.add_paragraph('This section was dynamically generated by scanning the project directory:')
    
    p = doc.add_paragraph()
    p.add_run('• Total Python Files (.py): ').bold = True
    p.add_run(str(stats['python_files']))
    
    p = doc.add_paragraph()
    p.add_run('• Total TypeScript Files (.ts): ').bold = True
    p.add_run(str(stats['ts_files']))
    
    p = doc.add_paragraph()
    p.add_run('• Total React Files (.tsx): ').bold = True
    p.add_run(str(stats['tsx_files']))
    
    p = doc.add_paragraph()
    p.add_run('• Estimated Source Code Size: ').bold = True
    p.add_run(f"{stats['total_size_mb']:.2f} MB")
    
    doc.add_heading('Top-Level Directories', level=2)
    for d in top_dirs:
        p = doc.add_paragraph()
        p.add_run(f'📂 {d}').bold = True
        
    doc.save(filepath)
    print("Project scan results appended to Letter-Head.docx")

if __name__ == "__main__":
    append_scan_results()
